mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'
