mod 'cargomedia/php5',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/php5'

mod 'cargomedia/nginx',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nginx'

mod 'cargomedia/mysql',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mysql'

mod 'cargomedia/rsync',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/rsync'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/dotdeb',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/dotdeb'
