mod 'cargomedia/sysvinit',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/sysvinit'

mod 'cargomedia/systemd',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/systemd'

mod 'cargomedia/monit',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/monit'

mod 'cargomedia/ufw',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/ufw'
