mod 'cargomedia/nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'cargomedia/logrotate',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/nginx',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nginx'

mod 'cargomedia/mjr_convert',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mjr_convert'

mod 'cargomedia/lame',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/lame'

mod 'cargomedia/fluentd',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/fluentd'
