logfile: /var/log/bipbip/<%= @log_file %>
loglevel: <%= @log_level %>
logfile_days_to_keep: <%= @logfile_days_to_keep %>
logfile_maxsize: <%= @logfile_maxsize %>
frequency: <%= @frequency %>
include: services.d/

storages:
  -
    name: copperegg
    api_key: <%= @api_key %>
