loglevel: <%= @log_level %>
frequency: <%= @frequency %>
include: services.d/

<% if @server_tag_list and not @server_tag_list.empty? %>
tags:
<%= @server_tag_list.map { |t| "  - " + t if t != '' }.join("\n") %>
<% end %>

storages:
<% if @api_key %>  -
    name: copperegg
    api_key: <%= @api_key %>
<% end %>
