source 'https://rubygems.org'

gem 'rake', '~>10.4'
gem 'puppet-lint', '~>1.1'
gem 'puppet', '~>3.7'
gem 'rspec-core', '~>3.1'
gem 'serverspec', '~>2.8'
gem 'specinfra', '~>2.12'
gem 'puppet-syntax', '~>1.4'
gem 'event_emitter', '~>0.2.5'
gem 'chronic_duration', '~>0.10.6'
gem 'komenda', '~> 0.0.3'
gem 'indentation', '~> 0.1.1'
