source 'https://rubygems.org'

gem 'rake', '~> 11.3'
gem 'puppet-lint', '~> 2.2'
gem 'puppet', '~> 4.7.0'
gem 'rspec-core', '~> 3.5'
gem 'serverspec', '~> 2.8'
gem 'specinfra', '~> 2.12'
gem 'puppet-syntax', '~> 2.4'
gem 'event_emitter', '~> 0.2.5'
gem 'colorize', '~> 0.8.1'
gem 'chronic_duration', '~> 0.10.6'
gem 'komenda', '~> 0.1.4'
gem 'indentation', '~> 0.1.1'
gem 'net-ssh', '~> 3.2.0'
