mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/ssh',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/ssh'

mod 'cargomedia/git',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'cargomedia/apt',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/puppet',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/puppet'

mod 'cargomedia/postgresql',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/postgresql'

mod 'cargomedia/ufw',
    :git => 'git://github.com/cargomedia/puppet-packages.git',
    :path => 'modules/ufw'
