mod 'capistrano',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/capistrano'

mod 'git',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'ruby',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ruby'

mod 'environment',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/environment'
