mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/cron',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cron'
