#!/bin/sh

set -e

HOST="<%= @host %>"

echo "Restoring latest backup..."
rm -rf /tmp/restore-<%= @source %>
rdiff-backup --restore-as-of now /home/backup/<%= @source %> /tmp/restore-<%= @source %>

echo "Copying to $HOST..."
scp -pr -C -o CompressionLevel=9 /tmp/restore-<%= @source %> root@$HOST:<%= @destination %>
rm -rf /tmp/restore-<%= @source %>
