mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/sysvinit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/sysvinit'
