mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/apache2',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apache2'

mod 'cargomedia/ruby',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ruby'
