mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/helper',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/helper'

mod 'cargomedia/lightdm',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/lightdm'

mod 'cargomedia/accountsservice',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/accountsservice'

mod 'cargomedia/xpra',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/xpra'
