mod 'cargomedia/daemon',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/daemon'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/logrotate',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/git',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/fluentd',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/fluentd'

mod 'cargomedia/needrestart',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/needrestart'
