# Circular dependency not supported
#
#mod 'cargomedia/bipbip',
#  :git => 'git@github.com:cargomedia/puppet-packages.git',
#  :path => 'modules/bipbip'
#
#mod 'cargomedia/postfix',
#   :git => 'git@github.com:cargomedia/puppet-packages.git',
#   :path => 'modules/postfix'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'
