mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/logrotate',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'cargomedia/daemon',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/daemon'

mod 'cargomedia/ufw',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/ufw'
