#!/bin/bash

# mongod - Should no longer use this script. Puppet will use this script to confirm it has replaced the
# default package script

### BEGIN INIT INFO
# Provides:          mongod
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: An object/document-oriented database
# Description:       MongoDB is a high-performance, open source, schema-free
#                    document-oriented data store that's easy to deploy, manage
#                    and use. It's network accessible, written in C++ and offers
#                    the following features:
#
#                       * Collection oriented storage - easy storage of object-
#                         style data
#                       * Full index support, including on inner objects
#                       * Query profiling
#                       * Replication and fail-over support
#                       * Efficient storage of binary data including large
#                         objects (e.g. videos)
#                       * Automatic partitioning for cloud-level scalability
#
#                    High performance, scalability, and reasonable depth of
#                    functionality are the goals for the project.
### END INIT INFO


start()
{
  echo -n $"This is a dummy script.  Starting mongo should be done with /etc/init.d/mongod_* scripts"
  echo
  [ $RETVAL -eq 0 ]
}

stop()
{
  echo -n $"This is a dummy script.  Stopping mongo should be done with /etc/init.d/mongod_* scripts"
  echo
  [ $RETVAL -eq 0 ]
}

restart () {
  echo -n $"This is a dummy script. Restarting mongo should be done with /etc/init.d/mongod_* scripts"
  echo
  [ $RETVAL -eq 0 ]
}

status () {
  exit 1;
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "This script is no longer used.  Please refer to /etc/init.d/mongod_* scripts"
    RETVAL=1
esac

exit $RETVAL
