mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/gearman',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/gearman'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/logrotate',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'cargomedia/git',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'cargomedia/openssl',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/openssl'
