mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/apache2',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apache2'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/gearman',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/gearman'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'
