mod 'cargomedia/ca_certificates',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ca_certificates'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'
