mod 'ca-certificates',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/ca-certificates'

mod 'monit',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/monit'
