mod 'cargomedia/ca-certificates',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ca-certificates'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'
