mod 'cargomedia/nginx',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nginx'

mod 'cargomedia/daemon',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/daemon'

mod 'cargomedia/helper',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/helper'

mod 'puppetlabs/stdlib',
    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/ufw',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/ufw'

mod 'cargomedia/unzip',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/unzip'

mod 'cargomedia/apt',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/apt'
