mod 'monit',
  :git => 'git@github.com:njam/puppet-packages.git',
  :spec => 'deps',
  :path => 'modules/monit'

mod 'bipbip',
  :git => 'git@github.com:njam/puppet-packages.git',
  :spec => 'deps',
  :path => 'modules/bipbip'
