mod 'cargomedia/sysctl',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'cargomedia/ulimit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ulimit'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/database',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/database'
