mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/apt',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/nodejs',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'
