#!/bin/sh

### BEGIN INIT INFO
# Provides:					wowza
# Required-Start:		$all
# Required-Stop:		 $all
# Default-Start:		 2 3 4 5
# Default-Stop:			0 1 6
# Short-Description: Starts wowza
# Description:			 Starts wowza using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=wowza
DESC=wowza
DAEMON=/usr/bin/java
DAEMON_USER=wowza
JAVA_OPTS="-Xmx10000M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:NewSize=256m -server -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote=true"
WMSAPP_HOME=/usr/local/WowzaStreamingEngine
WMSCONFIG_HOME=/usr/local/WowzaStreamingEngine
DAEMON_OPTS="-Dcom.wowza.wms.runmode=service -Dcom.wowza.wms.native.base=linux -Dcom.wowza.wms.AppHome=${WMSAPP_HOME} -Dcom.wowza.wms.ConfigHome=${WMSCONFIG_HOME} -cp ${WMSAPP_HOME}/bin/wms-bootstrap.jar com.wowza.wms.bootstrap.Bootstrap"
PID_FILE=/var/run/${NAME}.pid
LOG_DIR=/var/log/wowza

set -e
. /lib/lsb/init-functions


case "${1}" in
	start)
		log_daemon_msg "Starting ${DESC}" "${NAME}"
		mkdir -p ${LOG_DIR}
		chown ${DAEMON_USER} ${LOG_DIR}
		ulimit -n 20000
		if (start-stop-daemon --start --pidfile ${PID_FILE} --make-pidfile --background --startas ${DAEMON} --chuid ${DAEMON_USER} --umask 0 -- ${JAVA_OPTS} ${DAEMON_OPTS} start); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	stop)
		log_daemon_msg "Stopping ${DESC}" "${NAME}"
		if (start-stop-daemon --stop --pidfile ${PID_FILE} --retry=TERM/20/KILL/5); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	status)
		status_of_proc -p ${PID_FILE} ${DAEMON} ${NAME}
	;;
	restart)
		${0} stop
		sleep 0.5
		${0} start
	;;
	*)
		echo "Usage: ${0} {start|stop|status|restart}" >&2
	;;
esac

exit 0
