mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/composer',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/composer'

mod 'cargomedia/php5',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/php5'

mod 'cargomedia/phpunit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/phpunit'

mod 'cargomedia/uglify',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/uglify'

mod 'cargomedia/browserify',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/browserify'

mod 'cargomedia/autoprefixer',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/autoprefixer'

mod 'cargomedia/foreman',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/foreman'

mod 'cargomedia/mysql',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mysql'

mod 'cargomedia/redis',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/redis'

mod 'cargomedia/memcached',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/memcached'

mod 'cargomedia/elasticsearch',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/elasticsearch'

mod 'cargomedia/gearman',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/gearman'

mod 'cargomedia/socket_redis',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/socket_redis'

mod 'cargomedia/nginx',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nginx'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/mongodb',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mongodb'

mod 'cargomedia/cm_janus',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cm_janus'

mod 'cargomedia/janus',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/janus'

mod 'cargomedia/ufw',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ufw'

mod 'cargomedia/phantomjs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/phantomjs'

mod 'cargomedia/systemd',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/systemd'
