#!/bin/bash

ps ax | grep 'expand-raid.sh' | grep -v 'grep' | grep -qv $$
STATUS=$?
if [ $STATUS == 0 ]; then
		echo 'Verify that expand-raid.sh is not running'
		exit 1
fi

set -e

DIFFFILE=/var/run/expand-raid
BUILDING=false
if (test -f ${DIFFFILE}) then
	if [ $STATUS -gt 0 ] && (arcconf getstatus 1 | grep -q 'Build/Verify') then
		BUILDING=true
	else
		rm ${DIFFFILE}
	fi
fi

if !($BUILDING) then
	parted -l >${DIFFFILE}
	read -p 'Please enter the drive numbers, e.g. 0 12 0 13 >' -e DRIVES
	read -p 'Please enter a name for the new RAID, e.g. cargo-raid3 (Max 16 chars)>' -e NAME
	echo 'Starting to build array'
	arcconf create 1 logicaldrive name ${NAME} method build MAX 1 ${DRIVES} noprompt
	echo
	echo 'Progress'
else
	echo 'Building is still happening, re-enabling the monitor'
fi

PERCENT="0%"
while !(test -z "$PERCENT") do
	PERCENT=$(arcconf getstatus 1 | grep 'Percentage' | cut -d ':' -f2 | sed 's/^[[:space:]]*//g')
	echo -ne "$PERCENT%\r"
	sleep 4
done
echo 'Starting to expand lvm...'
LVM_NAME=/dev/<%= @volumeGroupName %>/<%= @logicalVolumeName %>
NEWDEVICE=$(parted -l | diff - ${DIFFFILE} | awk '/dev/{print substr($4,0,length($4))}')
pvcreate ${NEWDEVICE}
vgextend vg01 ${NEWDEVICE}
lvextend -l 90%VG ${LVM_NAME}
xfs_growfs ${LVM_NAME}
rm ${DIFFFILE}
echo 'Done.'
