mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/ssh',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/ssh'

mod 'cargomedia/helper',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/git',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'cargomedia/ruby',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/ruby'

mod 'cargomedia/librarian_puppet',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/librarian_puppet'

mod 'cargomedia/rsync',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/rsync'

mod 'cargomedia/apt',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/daemon',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/daemon'

mod 'cargomedia/bipbip',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/bipbip'
