mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/ssh',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ssh'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/git',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/git'

mod 'cargomedia/ruby',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ruby'

mod 'cargomedia/librarian_puppet',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/librarian_puppet'

mod 'cargomedia/passenger',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/passenger'

mod 'cargomedia/apache2',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apache2'

mod 'cargomedia/cgroups',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cgroups'

mod 'cargomedia/rsync',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/rsync'
