mod 'nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'
