mod 'cargomedia/janus',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/janus'

mod 'cargomedia/ffmpeg',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ffmpeg'
