#! /bin/sh
### BEGIN INIT INFO
# Provides:          cgconfig-apply
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Cgroups
# Description:       Cgroups configuration apply tool
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Cgroups configuration apply"
NAME=cgconfigparser
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="-l /etc/cgconfig.conf"
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

. /lib/lsb/init-functions

do_start()
{
	$DAEMON $DAEMON_ARGS
}

case "$1" in
  start|apply|reload)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|apply|reload}" >&2
	exit 3
	;;
esac
