#! /bin/sh
### BEGIN INIT INFO
# Provides:          cgconfig-apply
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Cgroups
# Description:       Cgroups configuration apply tool
### END INIT INFO

NAME=cgconfig-apply
DESC=cgconfig-apply
DAEMON=/usr/sbin/cgconfigparser
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON_ARGS="-l /etc/cgconfig.conf"

test -x ${DAEMON} || exit 0
set -e
. /lib/lsb/init-functions

do_start()
{
	$DAEMON $DAEMON_ARGS
}

case "$1" in
	start|apply|reload)
	  log_daemon_msg "Applying $DESC" "$NAME"
	  do_start
	  log_end_msg 0
	;;
  *)
	echo "Usage: ${0} {start|apply|reload}" >&2
	;;
esac
