mod 'cargomedia/cgi-fcgi',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cgi-fcgi'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'
