mod 'cargomedia/cgi_fcgi',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cgi_fcgi'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'
