mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/sysctl',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/daemon',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/daemon'
