mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/sysctl',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/sysctl'
