mod 'apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'
