mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/python',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/python'

mod 'cargomedia/unzip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/unzip'
