mod 'cargomedia/augeas',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/augeas'

mod 'cargomedia/sysctl',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'cargomedia/apt',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/apt'
