mod 'cargomedia/augeas',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/augeas'

mod 'cargomedia/mount',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mount'

mod 'cargomedia/sysvinit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/sysvinit'

mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'
