mod 'cargomedia/augeas',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/augeas'

mod 'cargomedia/mount',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mount'
