mod 'cargomedia/apt',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/apt'

mod 'cargomedia/systemd',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/systemd'
