mod 'cargomedia/apt',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/helper',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/helper'

mod 'cargomedia/java',
   :git => 'git@github.com:cargomedia/puppet-packages.git',
   :path => 'modules/java'
