mod 'cargomedia/java',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/java'

mod 'cargomedia/ffmpeg',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ffmpeg'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'
