mod 'cargomedia/deb-multimedia',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/deb-multimedia'

mod 'cargomedia/yasm',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/yasm'

mod 'cargomedia/x264',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/x264'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'
