mod 'cargomedia/mount',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/mount'

mod 'cargomedia/raid',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/raid'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'
