mod 'mount',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/mount'

mod 'raid',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/raid'

mod 'monit',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/monit'

mod 'helper',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/helper'
