mod 'cargomedia/helper',
  :git => 'git://github.com/cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'cargomedia/apt',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/apt'

mod 'cargomedia/ufw',
   :git => 'git://github.com/cargomedia/puppet-packages.git',
   :path => 'modules/ufw'

mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
