mod 'build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'

mod 'helper',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/helper'

mod 'yasm',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/yasm'
