mod 'cargomedia/cm',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cm'

mod 'cargomedia/composer',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/composer'

mod 'cargomedia/gdisk',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/gdisk'
