mod 'cargomedia/apt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apt'

mod 'cargomedia/bipbip',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'cargomedia/ufw',
    :git => 'git@github.com:cargomedia/puppet-packages.git',
    :path => 'modules/ufw'
