#!/bin/sh

### BEGIN INIT INFO
# Provides:				foo
# Required-Start:		$all
# Required-Stop:		$all
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:    Starts foo
# Description:			Starts foo using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=foo
DESC=foo
DAEMON=/tmp/bar
DAEMON_USER=root
PID_FILE=/var/run/${NAME}.pid

set -e
. /lib/lsb/init-functions


case "${1}" in
	start)
		log_daemon_msg "Starting ${DESC}" "${NAME}"
		ulimit -c unlimited
		if (start-stop-daemon --start --pidfile ${PID_FILE} --make-pidfile --background --startas ${DAEMON} --chuid ${DAEMON_USER} --umask 0 -- start); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	stop)
		log_daemon_msg "Stopping ${DESC}" "${NAME}"
		if (start-stop-daemon --stop --oknodo --retry=TERM/20/TERM/20 --pidfile ${PID_FILE}); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	status)
		status_of_proc -p ${PID_FILE} ${DAEMON} ${NAME}
	;;
	restart)
		${0} stop
		sleep 0.5
		${0} start
	;;
	*)
		echo "Usage: ${0} {start|stop|status|restart}" >&2
	;;
esac

exit 0
