mod 'cargomedia/nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/daemon',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/daemon'
