mod 'apt',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/apt'

mod 'php5',
  :git => 'git@github.com:njam/puppet-packages.git',
  :ref => 'deps',
  :path => 'modules/php5'
