mod 'rdiff-backup',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/rdiff-backup'

mod 'ssh',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/ssh'
