mod 'cargomedia/nodejs',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/nodejs'

mod 'cargomedia/monit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/monit'

mod 'cargomedia/logrotate',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/logrotate'

mod 'cargomedia/sysvinit',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/sysvinit'
