mod 'cargomedia/cuda',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cuda'

mod 'cargomedia/build',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/build'
