mod 'cargomedia/apache2',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/apache2'

mod 'cargomedia/php5',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/php5'
